export const fourStarReviews: string[] = [
  "The tour was really well done. The leasing agent was knowledgeable and answered all my questions. The unit itself was a little smaller than I expected but still a solid option.",
  "Great experience overall. The staff was friendly and the building was clean and well-maintained. I'd definitely consider applying here.",
  "Really enjoyed the tour. The leasing agent was patient and thorough, and the common areas looked great. A few things I'd want to know more about before committing, but a strong first impression.",
  "Smooth process from start to finish. Easy to schedule, the tour ran on time, and the agent was helpful. The apartment is high on my list.",
  "The tour gave me a good feel for the community. Staff was warm and professional. I have a couple of small reservations but overall a very positive visit.",
  "Nice tour experience. The unit had a great layout and the building was quiet. The leasing office was easy to work with.",
  "I appreciated how prepared the leasing agent was. They had all the pricing and availability info ready without me having to ask. Would recommend touring here.",
  "The property is well-kept and the staff made me feel welcome. It wasn't a perfect fit for everything I'm looking for, but it's definitely in my top choices.",
  "Solid tour. The agent walked me through everything clearly and didn't rush me. The unit itself was nice, just weighing my options before deciding.",
  "Really liked the vibe of the building. The tour was organized and the leasing agent was easy to talk to. Would come back for a second look.",
  "The leasing team was great, responsive before the tour and personable during it. The apartment checked most of my boxes.",
  "Good tour. The unit was clean and the building amenities were better than expected. I have a few logistical questions to sort out but I'm interested.",
  "The staff here clearly takes pride in the property. The tour was thorough and I left feeling informed. Solid option.",
  "Appreciated the honesty from the leasing agent about what's included and what isn't. Refreshing compared to some other places I've toured. Apartment itself was nice.",
  "Very welcoming atmosphere. The agent knew the building well and gave a genuine, relaxed tour. Left with a good impression.",
  "The tour was informative and low-pressure. The unit had nice natural light and the floor plan worked well. Putting this one high on my list.",
  "Clean, well-managed building with a friendly leasing team. A few things I'd want to clarify before signing, but the tour itself was great.",
  "I've toured a lot of apartments lately and this was one of the better experiences. The agent was attentive and the unit showed well.",
  "Good first impression. The leasing office was easy to work with and the apartment was in great condition. Narrowing down my options but this is still in the running.",
  "The agent took time to understand what I was looking for before showing me units. That kind of personalized approach made a real difference.",
  "Really nice property. The hallways and common areas were clean and the units were well-maintained. Gave it four stars only because I'm still comparing a few places.",
  "Straightforward, no-pressure tour. The leasing agent was helpful and the unit had a good layout. Strong contender for my next place.",
  "The tour was a great use of my time. The agent covered everything I needed to know and the unit itself was exactly as described online.",
  "Friendly staff, clean building, nice unit. I have a couple of questions to follow up on but this place made a good impression.",
  "The leasing agent was professional and clearly knew the property well. The tour felt organized without being overly formal. Liked what I saw.",
  "Good experience overall. The building had a calm, well-maintained feel and the staff was easy to talk to. Weighing my options but definitely interested.",
  "The tour ran smoothly and the unit was in great shape. The leasing team was helpful without being pushy. Still deciding but this place stands out.",
  "Appreciated how quickly they got back to me to schedule the tour. The visit itself was thorough and the agent answered every question I had.",
  "Solid apartment in a well-run building. The tour was efficient and the leasing agent was personable. A few minor things I'd want to confirm, but overall very positive.",
  "The property felt well-managed and the staff seemed genuinely invested in the residents' experience. Good tour, good vibe.",
  "I liked that the tour wasn't rushed. The agent let me take my time in the unit and ask questions at my own pace. Left feeling good about the place.",
  "Nice building and a genuinely helpful leasing team. This is one of the stronger options I've seen in my search so far.",
  "The leasing agent was knowledgeable and straightforward, no upselling, just honest answers. The unit itself was clean and well-laid-out.",
  "Really good experience. The building is in great condition and the staff clearly cares about keeping it that way. Still have a few things to compare but this is high on my list.",
  "The tour gave me everything I needed to make an informed decision. Agent was great, unit looked good. Just a few details to sort out.",
  "Comfortable, well-kept building with a professional leasing team. I'd feel good living here, just want to look at one or two more options first.",
  "Clean building, friendly staff, and a unit that actually matched the photos online. That alone puts this place ahead of a few others I've toured.",
  "The tour was easy to schedule and the visit itself was thorough. Agent was personable and the apartment had a nice feel to it.",
  "Really positive visit. The agent walked me through the unit without making it feel like a sales pitch. I'm seriously considering applying.",
  "Loved the layout of the unit and the building felt well-managed. The leasing team was responsive and easy to work with from the start.",
  "The tour covered everything I wanted to see and the agent was happy to answer follow-up questions. Very close to being exactly what I'm looking for.",
  "Smooth, professional tour experience. The building was clean and quiet, which is a big deal for me. Leaving with a good feeling about this place.",
  "Good tour, thorough and unhurried, and the agent was easy to talk to. The unit had a great layout. Still in the decision phase but this is near the top.",
  "The leasing agent was well-prepared and genuinely enthusiastic about the property. The apartment showed really well.",
  "I appreciated the attention to detail during the tour. The building is well-maintained and the unit was in great condition. Solid option.",
  "Nice property with a professional team. The tour was informative without being overwhelming. I could see myself living here.",
  "Good experience from start to finish. The leasing team was communicative, the tour was organized, and the unit was exactly what I was hoping to see.",
  "The building had a calm, clean feel and the staff matched that energy, friendly and professional. Left the tour with a really positive impression.",
  "Really liked the unit layout and the overall feel of the building. The leasing agent was helpful and didn't pressure me at all. Seriously considering this one.",
  "The tour was one of the smoother ones I've had in my apartment search. The agent knew their stuff and the apartment showed well. Definitely in my top picks.",
];

export const fiveStarReviews: string[] = [
  "Absolutely loved the tour. The leasing agent was fantastic, warm, knowledgeable, and genuinely helpful. The apartment itself blew me away. Can't imagine finding a better fit.",
  "This was hands down the best apartment tour I've been on. The staff made me feel at home from the moment I walked in. I applied on the spot.",
  "Amazing experience. The unit was beautiful and the leasing team went above and beyond to answer every question I had. Highly recommend touring here.",
  "I've toured a lot of apartments and this one stood out immediately. The building is immaculate, the staff is incredible, and the unit was exactly what I'd been hoping to find.",
  "The leasing agent was the highlight of the tour, personable, knowledgeable, and made the whole process feel effortless. The apartment didn't hurt either. Stunning space.",
  "From the moment I scheduled my tour to the moment I left, everything was exceptional. The team here is genuinely great and the property shows it.",
  "I walked in not expecting much and walked out ready to sign a lease. The unit was gorgeous and the agent made the whole experience enjoyable.",
  "Best tour experience I've had in a long time. The leasing team is clearly proud of the property and it shows. It's really impressive.",
  "The apartment exceeded my expectations in every way. The leasing agent was wonderful, patient, thorough, and easy to talk to. This is the one.",
  "I couldn't have asked for a better tour. The building is beautiful, the staff is professional and warm, and the unit checked every box. Loved it.",
  "Phenomenal tour from start to finish. The leasing agent walked me through every detail and made me feel genuinely welcome. This property is something special.",
  "Toured a handful of places this week and this one was a clear standout. The building is well-maintained, the unit is gorgeous, and the staff is exceptional.",
  "The leasing agent was so easy to work with, no pressure, just honest and helpful. The apartment itself is stunning. This place has everything.",
  "I came in with a long list of questions and the agent had answers for every single one. Impressed by the staff and absolutely in love with the unit.",
  "This tour completely changed my apartment search. The building is beautiful, the community feels great, and the leasing team made the whole thing enjoyable. Applying today.",
  "One of the best apartment experiences I've ever had. The tour felt genuine and personal, and the unit itself is stunning.",
  "The leasing agent was incredible, knowledgeable, genuinely friendly, and just easy to talk to throughout the whole tour. The apartment is just as impressive.",
  "I wasn't expecting to fall in love with a place on my first tour, but here we are. The unit is beautiful and the staff is wonderful.",
  "Exceptional tour. The leasing team is top-notch and the property is clearly very well cared for. This is exactly the kind of place I've been looking for.",
  "The whole experience felt effortless. Easy to schedule, the agent was fantastic, and the apartment was even better in person than in the photos.",
  "Walked out of this tour feeling genuinely excited about where I might be living. The agent was great, the building is gorgeous, and the unit had everything I was hoping for.",
  "The leasing team was warm, professional, and incredibly helpful. The tour was thorough and the apartment was stunning. Best place I've seen in my search.",
  "I've been apartment hunting for weeks and this tour reminded me why I started looking in the first place. Incredible unit, incredible staff.",
  "The leasing agent made the experience really special. They were genuinely enthusiastic about the property and it came through. The apartment lives up to the hype.",
  "Everything about this tour was impressive. The building is beautiful, the unit layout is perfect, and the leasing agent was an absolute pleasure to work with.",
  "This place is the real deal. The tour was professional and personal at the same time, and the apartment itself is everything I was hoping to find.",
  "Loved every minute of the tour. The leasing agent was incredibly knowledgeable and the unit was in perfect condition. Can't stop thinking about this apartment.",
  "The staff here sets a really high bar. From scheduling to the tour itself, everything was smooth, professional, and genuinely enjoyable.",
  "I went in with realistic expectations and left completely sold. The unit is beautiful, the building is well-run, and the team made the whole tour a great experience.",
  "Outstanding tour. The leasing agent answered every question I had and genuinely made me feel valued. The apartment was gorgeous.",
  "The tour gave me everything I needed and more. The agent was fantastic and the unit blew me away. I knew by the end of the tour that this was the one.",
  "Incredible experience from start to finish. The property is impeccably maintained and the leasing team is genuinely exceptional. Highly recommend.",
  "The leasing agent made the tour feel personal and unhurried. The building is beautiful and the unit exceeded every expectation I had. Loved it.",
  "I've been to a lot of apartment tours and this one stands apart. The staff is genuinely great and the property speaks for itself.",
  "Beautiful apartment, outstanding leasing team. The tour was one of the best experiences I've had in my search and the apartment is exactly what I was looking for.",
  "The building is gorgeous and the staff matches it. The leasing agent was wonderful, patient, helpful, and clearly passionate about the community.",
  "Couldn't be more impressed. The unit is stunning, the building is immaculate, and the leasing team made the whole experience smooth and enjoyable.",
  "The tour felt welcoming from the start. The agent was personable and knowledgeable, and the apartment was in perfect condition. Easily the best place I've toured.",
  "I walked in for a tour and walked out with a new favorite apartment. The leasing team is fantastic and the unit itself is gorgeous.",
  "Exceptional all around. The building is beautifully maintained, the leasing agent was excellent, and the unit checked every single box. Can't recommend this place enough.",
  "One of the most pleasant apartment tours I've been on. The agent was genuinely helpful and the unit was even better than I expected.",
  "The staff here really cares. You can feel it in how the building is maintained and how they treat you during the tour. The apartment itself is incredible.",
  "Loved this tour. The leasing agent was warm, thorough, and clearly knowledgeable. The unit is beautiful and the building feels like a real community.",
  "Absolutely the best apartment I've toured. The leasing team is wonderful and the unit is stunning. Already looking forward to calling this place home.",
  "The tour was flawless. The agent answered everything I asked without hesitation and the apartment was even more impressive in person. This is the one.",
  "I came in hoping to find a strong contender and left having found my top choice. The staff is excellent and the property is gorgeous.",
  "The leasing agent was the best I've encountered in my whole apartment search, genuine, helpful, and made the whole tour feel effortless. And the unit was stunning on top of that.",
  "This place has everything. Beautiful unit, well-maintained building, and a leasing team that actually makes you feel valued. Incredible experience.",
  "I'm usually pretty hard to impress on apartment tours, but this one won me over completely. The unit is gorgeous and the staff is exceptional.",
  "Best apartment tour I've been on, full stop. The building is stunning, the leasing team is wonderful, and I left the tour genuinely excited. Highly recommend.",
];
